---
title: "Music and Emotions: Unraveling the Connection"
author: "Tilina Alzaben"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(quanteda)
library(quanteda.textstats)
library(tibble)
library(tidytext)
library(kableExtra)
library(stopwords)
library(SnowballC)
library(wordcloud)
library(ggplot2)
```

```{r}
# Loading Data
lyrics <- read.csv("~/Text Analysis/song_lyrics_sample.csv")
genres <- c("country", "pop", "rap", "rb", "rock")

# Filtering to only include songs after the year 1900, and only the following genres: country, pop, rap, rhythm and blues, and rock music
lyrics <- lyrics %>%
  filter(!is.na(year) & grepl("^\\d{4}$", year)) %>%
  mutate(year = as.numeric(year)) %>%
  filter(year >= 1900, tag %in% genres) %>%
  mutate(tag = ifelse(tag == "rb", "rhythm and blues", tag)) %>% 
  select(tag, lyrics)

# Data Dimensions
dim(lyrics)

```

*Table 1*: Lyrics Corpus
```{r}
# Calculating the total number of tokens in the lyrics corpus
total_tokens <- lyrics %>%
  unnest_tokens(word, lyrics) %>%
  count() %>%
  summarize(total_tokens = sum(n))

# Calculating the number of songs in the lyrics corpus
total_files <- lyrics %>%
  distinct(lyrics) %>%
  summarize(total_files = n_distinct(lyrics))

# Creating a summary table
summary_table <- tibble(
  "Metric" = c("Words (tokens)", "Songs"),
  "Value" = c(total_tokens$total_tokens, total_files$total_files)
)

kableExtra::kbl(summary_table, caption = "Summary of Lyrics Corpus", booktabs = T, linesep = "") %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()

```

*Table 2*: Song Frequency and Tokens by Genre
```{r}
# Calculating the total number of tokens for each genre
total_tokens <- lyrics %>%
  group_by(tag) %>%
  unnest_tokens(word, lyrics) %>%
  count() %>%
  summarize(total_tokens = sum(n))

# Creating a table of the "tag" variable with genre frequencies
tag_table <- table(lyrics$tag)

# Converting the table to a data frame
tag_df <- as.data.frame(tag_table)

# Joining the total_tokens data frame based on the "Genre" column
tag_df <- merge(tag_df, total_tokens, by.x = "Var1", by.y = "tag")

# Renaming the columns
colnames(tag_df) <- c("Genre", "Frequency", "Tokens")

kableExtra::kbl(tag_df, caption = "Number of Songs and Tokens by Genre", booktabs = T, linesep = "") %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

*Table 3*: Word Frequency for All Genres
```{r, message = FALSE}
# Creating tokens, and removing stopwords
tokenized_lyrics <- lyrics %>%
  unnest_tokens(word, lyrics) %>%
  filter(!(word %in% stop_words$word), 
         !nchar(word) < 3) %>%
  mutate(stem = wordStem(word))

token_summary <- tokenized_lyrics %>%
  group_by(word) %>%
  count() %>%
  ungroup()

# Creating a word cloud for all genres
wordcloud(words = token_summary$word, 
          freq = token_summary$n, 
          random.order = FALSE, 
          max.words = 100, 
          colors = brewer.pal(8, "Dark2"))
```

*Table 4*: Distinct Word Counts per Genre
```{r}
genre_word_summary <- tokenized_lyrics %>%
  group_by(tag) %>%
  summarize(word_count = n_distinct(word)) %>%
  distinct() %>%
  ungroup()

ggplot(genre_word_summary, aes(x = tag, y = word_count, fill = tag)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Genre", y = "Distinct Word Count per Genre", 
       title = "Lexical Diversity by Genre", 
       fill = "Genre") +
  theme_minimal()
```

*Table 5*: Term Frequency-Inverse Document Frequency
```{r}
tokenized_lyrics_summary <- tokenized_lyrics %>%
  group_by(tag, word) %>%
  count() 

tokenized_lyrics_summary <- tokenized_lyrics_summary %>%
  bind_tf_idf(word, tag, n) 

tokenized_lyrics_summary %>%
  group_by(tag) %>%
  slice_max(tf_idf, n = 5, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(word = reorder_within(word, tf_idf, tag)) %>%
  ggplot(aes(y = tf_idf, x = word), alpha = 0.05) + 
  geom_col() + 
  coord_flip() +
  scale_x_reordered() + 
  facet_wrap(~ tag, ncol = 2, scales = "free") + 
  labs(y = "TF-IDF", x = NULL)
```

*Table 6*: The Frequency of Emotions by Genre
```{r, message = FALSE}
lyrics_sentiment_sub <- tokenized_lyrics %>%
  inner_join(get_sentiments("nrc")) %>%
  filter(!sentiment %in% c("positive", "negative")) %>%
  distinct(tag, word, sentiment)

lyrics_sentiment_sub %>%
  count(tag, sentiment) %>%
  mutate(sentiment = reorder(sentiment, n)) %>%
  ggplot(aes(sentiment, n, fill = sentiment)) +
  geom_col() +
  facet_wrap(~ tag, scales = "free_x", labeller = label_both) +
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(x = NULL, y = NULL) +
  ggtitle("NRC Sentiment Song Analysis") +
  coord_flip()

```

*Table 7*: Frequency of Positive and Negative Words by Genre
```{r, message = FALSE}
lyrics_sentiment <- tokenized_lyrics %>%
  inner_join(get_sentiments("bing")) %>%
  distinct(tag, word, sentiment)

lyrics_sentiment %>%
  group_by(tag, sentiment) %>%
  summarize(n_words = n()) %>%
  ungroup() %>%
  group_by(tag) %>%
  mutate(total_assigned_words = sum(n_words)) %>%
  ungroup() %>%
  mutate(tag = fct_reorder(tag, total_assigned_words)) %>%
  ggplot(aes(x = tag, y = n_words, 
             fill = sentiment)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  scale_fill_manual(values = c("steelblue", "pink")) + 
  theme_bw() + 
  theme(legend.position = "bottom") +
  labs(title = "Positive and Negative Sentiment by Genre", 
       y = "Genre", x = "Number of Words")

```
